// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package protobuf.protobuf;

import protobuf.StudentOuterClass;

public final class PersonInfo {
  private PersonInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface person_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.person_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>int32 sex = 4;</code>
     */
    int getSex();

    /**
     * <code>float weight = 5;</code>
     */
    float getWeight();

    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    boolean hasInfo();
    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    PersonInfo.info_data getInfo();
    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    PersonInfo.info_dataOrBuilder getInfoOrBuilder();

    /**
     * <code>.Student student = 7;</code>
     */
    boolean hasStudent();
    /**
     * <code>.Student student = 7;</code>
     */
    StudentOuterClass.Student getStudent();
    /**
     * <code>.Student student = 7;</code>
     */
    StudentOuterClass.StudentOrBuilder getStudentOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.person_data}
   */
  public  static final class person_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.person_data)
      person_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use person_data.newBuilder() to construct.
    private person_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private person_data() {
      id_ = 0L;
      name_ = "";
      age_ = 0;
      sex_ = 0;
      weight_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private person_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 32: {

              sex_ = input.readInt32();
              break;
            }
            case 45: {

              weight_ = input.readFloat();
              break;
            }
            case 50: {
              PersonInfo.info_data.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(PersonInfo.info_data.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              StudentOuterClass.Student.Builder subBuilder = null;
              if (student_ != null) {
                subBuilder = student_.toBuilder();
              }
              student_ = input.readMessage(StudentOuterClass.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(student_);
                student_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonInfo.internal_static_protobuf_person_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonInfo.internal_static_protobuf_person_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonInfo.person_data.class, PersonInfo.person_data.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>int32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 5;
    private float weight_;
    /**
     * <code>float weight = 5;</code>
     */
    public float getWeight() {
      return weight_;
    }

    public static final int INFO_FIELD_NUMBER = 6;
    private PersonInfo.info_data info_;
    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    public PersonInfo.info_data getInfo() {
      return info_ == null ? PersonInfo.info_data.getDefaultInstance() : info_;
    }
    /**
     * <code>.protobuf.info_data info = 6;</code>
     */
    public PersonInfo.info_dataOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    public static final int STUDENT_FIELD_NUMBER = 7;
    private StudentOuterClass.Student student_;
    /**
     * <code>.Student student = 7;</code>
     */
    public boolean hasStudent() {
      return student_ != null;
    }
    /**
     * <code>.Student student = 7;</code>
     */
    public StudentOuterClass.Student getStudent() {
      return student_ == null ? StudentOuterClass.Student.getDefaultInstance() : student_;
    }
    /**
     * <code>.Student student = 7;</code>
     */
    public StudentOuterClass.StudentOrBuilder getStudentOrBuilder() {
      return getStudent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (sex_ != 0) {
        output.writeInt32(4, sex_);
      }
      if (weight_ != 0F) {
        output.writeFloat(5, weight_);
      }
      if (info_ != null) {
        output.writeMessage(6, getInfo());
      }
      if (student_ != null) {
        output.writeMessage(7, getStudent());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (weight_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, weight_);
      }
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getInfo());
      }
      if (student_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getStudent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PersonInfo.person_data)) {
        return super.equals(obj);
      }
      PersonInfo.person_data other = (PersonInfo.person_data) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getSex()
          == other.getSex());
      result = result && (
          java.lang.Float.floatToIntBits(getWeight())
          == java.lang.Float.floatToIntBits(
              other.getWeight()));
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && (hasStudent() == other.hasStudent());
      if (hasStudent()) {
        result = result && getStudent()
            .equals(other.getStudent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getWeight());
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (hasStudent()) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + getStudent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PersonInfo.person_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.person_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.person_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.person_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.person_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.person_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.person_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonInfo.person_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonInfo.person_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PersonInfo.person_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonInfo.person_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonInfo.person_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PersonInfo.person_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.person_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.person_data)
        PersonInfo.person_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonInfo.internal_static_protobuf_person_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonInfo.internal_static_protobuf_person_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonInfo.person_data.class, PersonInfo.person_data.Builder.class);
      }

      // Construct using PersonInfo.person_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        age_ = 0;

        sex_ = 0;

        weight_ = 0F;

        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        if (studentBuilder_ == null) {
          student_ = null;
        } else {
          student_ = null;
          studentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonInfo.internal_static_protobuf_person_data_descriptor;
      }

      public PersonInfo.person_data getDefaultInstanceForType() {
        return PersonInfo.person_data.getDefaultInstance();
      }

      public PersonInfo.person_data build() {
        PersonInfo.person_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonInfo.person_data buildPartial() {
        PersonInfo.person_data result = new PersonInfo.person_data(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        result.weight_ = weight_;
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (studentBuilder_ == null) {
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonInfo.person_data) {
          return mergeFrom((PersonInfo.person_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonInfo.person_data other) {
        if (other == PersonInfo.person_data.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (other.getWeight() != 0F) {
          setWeight(other.getWeight());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasStudent()) {
          mergeStudent(other.getStudent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonInfo.person_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonInfo.person_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>int32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>int32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private float weight_ ;
      /**
       * <code>float weight = 5;</code>
       */
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>float weight = 5;</code>
       */
      public Builder setWeight(float value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float weight = 5;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0F;
        onChanged();
        return this;
      }

      private PersonInfo.info_data info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          PersonInfo.info_data, PersonInfo.info_data.Builder, PersonInfo.info_dataOrBuilder> infoBuilder_;
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public PersonInfo.info_data getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? PersonInfo.info_data.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public Builder setInfo(PersonInfo.info_data value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public Builder setInfo(
          PersonInfo.info_data.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public Builder mergeInfo(PersonInfo.info_data value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              PersonInfo.info_data.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public PersonInfo.info_data.Builder getInfoBuilder() {
        
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      public PersonInfo.info_dataOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              PersonInfo.info_data.getDefaultInstance() : info_;
        }
      }
      /**
       * <code>.protobuf.info_data info = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PersonInfo.info_data, PersonInfo.info_data.Builder, PersonInfo.info_dataOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PersonInfo.info_data, PersonInfo.info_data.Builder, PersonInfo.info_dataOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private StudentOuterClass.Student student_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          StudentOuterClass.Student, StudentOuterClass.Student.Builder, StudentOuterClass.StudentOrBuilder> studentBuilder_;
      /**
       * <code>.Student student = 7;</code>
       */
      public boolean hasStudent() {
        return studentBuilder_ != null || student_ != null;
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public StudentOuterClass.Student getStudent() {
        if (studentBuilder_ == null) {
          return student_ == null ? StudentOuterClass.Student.getDefaultInstance() : student_;
        } else {
          return studentBuilder_.getMessage();
        }
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public Builder setStudent(StudentOuterClass.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          student_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public Builder setStudent(
          StudentOuterClass.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          student_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public Builder mergeStudent(StudentOuterClass.Student value) {
        if (studentBuilder_ == null) {
          if (student_ != null) {
            student_ =
              StudentOuterClass.Student.newBuilder(student_).mergeFrom(value).buildPartial();
          } else {
            student_ = value;
          }
          onChanged();
        } else {
          studentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = null;
          onChanged();
        } else {
          student_ = null;
          studentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public StudentOuterClass.Student.Builder getStudentBuilder() {
        
        onChanged();
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Student student = 7;</code>
       */
      public StudentOuterClass.StudentOrBuilder getStudentOrBuilder() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          return student_ == null ?
              StudentOuterClass.Student.getDefaultInstance() : student_;
        }
      }
      /**
       * <code>.Student student = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          StudentOuterClass.Student, StudentOuterClass.Student.Builder, StudentOuterClass.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              StudentOuterClass.Student, StudentOuterClass.Student.Builder, StudentOuterClass.StudentOrBuilder>(
                  getStudent(),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.person_data)
    }

    // @@protoc_insertion_point(class_scope:protobuf.person_data)
    private static final PersonInfo.person_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PersonInfo.person_data();
    }

    public static PersonInfo.person_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<person_data>
        PARSER = new com.google.protobuf.AbstractParser<person_data>() {
      public person_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new person_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<person_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<person_data> getParserForType() {
      return PARSER;
    }

    public PersonInfo.person_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface info_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.info_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string avatar = 1;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>string avatar = 1;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <code>string address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string education = 3;</code>
     */
    java.lang.String getEducation();
    /**
     * <code>string education = 3;</code>
     */
    com.google.protobuf.ByteString
        getEducationBytes();

    /**
     * <code>string job = 4;</code>
     */
    java.lang.String getJob();
    /**
     * <code>string job = 4;</code>
     */
    com.google.protobuf.ByteString
        getJobBytes();
  }
  /**
   * Protobuf type {@code protobuf.info_data}
   */
  public  static final class info_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.info_data)
      info_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use info_data.newBuilder() to construct.
    private info_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private info_data() {
      avatar_ = "";
      address_ = "";
      education_ = "";
      job_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private info_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              education_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              job_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonInfo.internal_static_protobuf_info_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonInfo.internal_static_protobuf_info_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonInfo.info_data.class, PersonInfo.info_data.Builder.class);
    }

    public static final int AVATAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object avatar_;
    /**
     * <code>string avatar = 1;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EDUCATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object education_;
    /**
     * <code>string education = 3;</code>
     */
    public java.lang.String getEducation() {
      java.lang.Object ref = education_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        education_ = s;
        return s;
      }
    }
    /**
     * <code>string education = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEducationBytes() {
      java.lang.Object ref = education_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        education_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOB_FIELD_NUMBER = 4;
    private volatile java.lang.Object job_;
    /**
     * <code>string job = 4;</code>
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      }
    }
    /**
     * <code>string job = 4;</code>
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, avatar_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      if (!getEducationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, education_);
      }
      if (!getJobBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, job_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, avatar_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      if (!getEducationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, education_);
      }
      if (!getJobBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, job_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PersonInfo.info_data)) {
        return super.equals(obj);
      }
      PersonInfo.info_data other = (PersonInfo.info_data) obj;

      boolean result = true;
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getEducation()
          .equals(other.getEducation());
      result = result && getJob()
          .equals(other.getJob());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + EDUCATION_FIELD_NUMBER;
      hash = (53 * hash) + getEducation().hashCode();
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + getJob().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PersonInfo.info_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.info_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.info_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.info_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.info_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonInfo.info_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonInfo.info_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonInfo.info_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonInfo.info_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PersonInfo.info_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonInfo.info_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonInfo.info_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PersonInfo.info_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.info_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.info_data)
        PersonInfo.info_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonInfo.internal_static_protobuf_info_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonInfo.internal_static_protobuf_info_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonInfo.info_data.class, PersonInfo.info_data.Builder.class);
      }

      // Construct using PersonInfo.info_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        avatar_ = "";

        address_ = "";

        education_ = "";

        job_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonInfo.internal_static_protobuf_info_data_descriptor;
      }

      public PersonInfo.info_data getDefaultInstanceForType() {
        return PersonInfo.info_data.getDefaultInstance();
      }

      public PersonInfo.info_data build() {
        PersonInfo.info_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonInfo.info_data buildPartial() {
        PersonInfo.info_data result = new PersonInfo.info_data(this);
        result.avatar_ = avatar_;
        result.address_ = address_;
        result.education_ = education_;
        result.job_ = job_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonInfo.info_data) {
          return mergeFrom((PersonInfo.info_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonInfo.info_data other) {
        if (other == PersonInfo.info_data.getDefaultInstance()) return this;
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getEducation().isEmpty()) {
          education_ = other.education_;
          onChanged();
        }
        if (!other.getJob().isEmpty()) {
          job_ = other.job_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonInfo.info_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonInfo.info_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <code>string avatar = 1;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar = 1;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 1;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 1;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object education_ = "";
      /**
       * <code>string education = 3;</code>
       */
      public java.lang.String getEducation() {
        java.lang.Object ref = education_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          education_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string education = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEducationBytes() {
        java.lang.Object ref = education_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          education_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string education = 3;</code>
       */
      public Builder setEducation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        education_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string education = 3;</code>
       */
      public Builder clearEducation() {
        
        education_ = getDefaultInstance().getEducation();
        onChanged();
        return this;
      }
      /**
       * <code>string education = 3;</code>
       */
      public Builder setEducationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        education_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object job_ = "";
      /**
       * <code>string job = 4;</code>
       */
      public java.lang.String getJob() {
        java.lang.Object ref = job_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          job_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string job = 4;</code>
       */
      public com.google.protobuf.ByteString
          getJobBytes() {
        java.lang.Object ref = job_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          job_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string job = 4;</code>
       */
      public Builder setJob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        job_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string job = 4;</code>
       */
      public Builder clearJob() {
        
        job_ = getDefaultInstance().getJob();
        onChanged();
        return this;
      }
      /**
       * <code>string job = 4;</code>
       */
      public Builder setJobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        job_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.info_data)
    }

    // @@protoc_insertion_point(class_scope:protobuf.info_data)
    private static final PersonInfo.info_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PersonInfo.info_data();
    }

    public static PersonInfo.info_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<info_data>
        PARSER = new com.google.protobuf.AbstractParser<info_data>() {
      public info_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new info_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<info_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<info_data> getParserForType() {
      return PARSER;
    }

    public PersonInfo.info_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_person_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_person_data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_info_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_info_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010protobuf\032\rstudent.proto\"\217\001" +
      "\n\013person_data\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022" +
      "\013\n\003age\030\003 \001(\005\022\013\n\003sex\030\004 \001(\005\022\016\n\006weight\030\005 \001(" +
      "\002\022!\n\004info\030\006 \001(\0132\023.protobuf.info_data\022\031\n\007" +
      "student\030\007 \001(\0132\010.Student\"L\n\tinfo_data\022\016\n\006" +
      "avatar\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\021\n\teducati" +
      "on\030\003 \001(\t\022\013\n\003job\030\004 \001(\tB\026\n\010protobufB\nPerso" +
      "nInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          StudentOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protobuf_person_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_person_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_person_data_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Sex", "Weight", "Info", "Student", });
    internal_static_protobuf_info_data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_info_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_info_data_descriptor,
        new java.lang.String[] { "Avatar", "Address", "Education", "Job", });
    StudentOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
